# HAd error with not indenting correctly - used GITHUB to check for errors
# https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
# :) :)

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Causes processes to be removed #ERROR - uses: actions/checkout@v2!!!!!
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        working-directory: client_two
      - run: npm run build
        working-directory: client_two
        env:
          CI: false
      - run: pm2 delete tweety_client
      - run: pm2 delete tweety_server
      - run: pm2 start npm --name "tweety_client" -- run start
        working-directory: client_two/build
      - run: npm i
        working-directory: ts_server
      - run: pm2 start npm --name "tweety_server" -- run start server.ts
        working-directory: ts_server
      - run: pm2 stop 0
      - run: pm2 start 0
      - run: pm2 stop 1
      - run: pm2 start 1
      - run: pm2 save
      - run: sudo service nginx restart
      - run: pm2 resurrect
